# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup GraalVM native-image
      run: |
        curl -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz --output graalvm-ce.tar.gz --silent --show-error
        tar -xzf graalvm-ce.tar.gz
        mv graalvm-ce-java11-20.0.0 graalvm-ce
        graalvm-ce/bin/gu install native-image
        sudo apt update
        sudo apt install build-essential
        sudo apt install libz-dev
    
    - name: Compile UberJAR
      run: |
        lein deps
        lein uberjar

    - name: Compile Native Image
      run: |
        cd target/uberjar
        ../../graalvm-ce/bin/native-image --initialize-at-build-time --allow-incomplete-classpath --no-fallback -H:+ReportExceptionStackTraces --report-unsupported-elements-at-runtime -jar ./gossip-0.1.0-SNAPSHOT-standalone.jar

    - name: Uploading the artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Gossip Native Image
        path: target/uberjar/gossip-0.1.0-SNAPSHOT-standalone
